### ISSUE TITLE
Example shows `filter` but actual expected input is `filters`

### ISSUE THREAD

**Issue by dhananjaipai** [tweedegolf/cleanup-images-action#1]
In the Readme
```yaml
      - uses: "tweedegolf/cleanup-images-action@main"
        with:
          package: debian
          filter: |-
            ^stable-\\d{2}-\\d{2}-\\d{4}$
            ^nightly-\\d{2}-\\d{2}-\\d{4}$
          keep_n: 5
```
update `filter` to `filters` as per `action.yml`
